INSERT INTO t_currency_kurs(F_CURRENCY, F_SALE, F_COST) values ('USD', 2.06, 2.15);
INSERT INTO t_currency_kurs(F_CURRENCY, F_SALE, F_COST) values ('EUR', 2.35, 2.40);
INSERT INTO t_currency_kurs(F_CURRENCY, F_SALE, F_COST) values ('RUB', 2.06, 2.15);

INSERT INTO t_credit(F_CURRENCY, F_MAX_SUM, F_MIN_SUM, F_CREADIT_NAME, F_PERCENT, F_PERIOD) VALUES ('BYN', 40000, 100, 'Кредит наличными', 26.9, 72);
INSERT INTO t_credit(F_CURRENCY, F_MAX_SUM, F_MIN_SUM, F_CREADIT_NAME, F_PERCENT, F_PERIOD) VALUES ('BYN', 5000, 100, 'Народный', 20, 48);
INSERT INTO t_credit(F_CURRENCY, F_MAX_SUM, F_MIN_SUM, F_CREADIT_NAME, F_PERCENT, F_PERIOD) VALUES ('BYN', 15000, 500, 'Горячее погашение', 16.4, 48);
INSERT INTO t_credit(F_CURRENCY, F_MAX_SUM, F_MIN_SUM, F_CREADIT_NAME, F_PERCENT, F_PERIOD) VALUES ('BYN', 5000, 300, 'Стандартный', 29, 48);
INSERT INTO t_credit(F_CURRENCY, F_MAX_SUM, F_MIN_SUM, F_CREADIT_NAME, F_PERCENT, F_PERIOD) VALUES ('BYN', 15000, 300, 'Доверие', 16.4, 48);


INSERT INTO t_deposit(F_CURRENCY, F_IS_REVERSAL, F_MIN_SUM, F_DEPOSIT_NAME, F_PERCENT, F_PERIOD) VALUES ('BYN', 'y', 50, 'Фреш', 13, 16);
INSERT INTO t_deposit(F_CURRENCY, F_IS_REVERSAL, F_MIN_SUM, F_DEPOSIT_NAME, F_PERCENT, F_PERIOD) VALUES ('RUB', 'y', 1600, 'Профит', 10.3, 9);
INSERT INTO t_deposit(F_CURRENCY, F_IS_REVERSAL, F_MIN_SUM, F_DEPOSIT_NAME, F_PERCENT, F_PERIOD) VALUES ('BYN', 'n', 50, 'Фикс', 13, 60);
INSERT INTO t_deposit(F_CURRENCY, F_IS_REVERSAL, F_MIN_SUM, F_DEPOSIT_NAME, F_PERCENT, F_PERIOD) VALUES ('BYN', 'y', 50, 'Актив', 8, 24);
INSERT INTO t_deposit(F_CURRENCY, F_IS_REVERSAL, F_MIN_SUM, F_DEPOSIT_NAME, F_PERCENT, F_PERIOD) VALUES ('USD', 'y', 200, 'Свободное накопление', 1.5, 48);
INSERT INTO t_deposit(F_CURRENCY, F_IS_REVERSAL, F_MIN_SUM, F_DEPOSIT_NAME, F_PERCENT, F_PERIOD) VALUES ('EUR', 'n', 200, 'Формула успеха', 1, 48);

INSERT INTO t_payment_category(F_NAME_CATEGORY) VALUES ('Билеты');
INSERT INTO t_payment_category(F_NAME_CATEGORY) VALUES ('Интернет, Телевидение');
INSERT INTO t_payment_category(F_NAME_CATEGORY) VALUES ('Интернет-магазины, Сервисы');
INSERT INTO t_payment_category(F_NAME_CATEGORY) VALUES ('МВД');
INSERT INTO t_payment_category(F_NAME_CATEGORY) VALUES ('Мобильная связь');
INSERT INTO t_payment_category(F_NAME_CATEGORY) VALUES ('СМИ');
INSERT INTO t_payment_category(F_NAME_CATEGORY) VALUES ('Таможенные платежи');
INSERT INTO t_payment_category(F_NAME_CATEGORY) VALUES ('Суды, Юридические услуги');

INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Belavia.by - авиабилеты Беларуси', '2931', 1);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Beltuz.by - театр юного зрителя', '4324471', 1);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Kvitki.by - оплата билетов', '4439161', 1);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Poezd.rw.by - ж/д билеты', '377801', 1);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Ticketpro.by - оплата билетов', '3311', 1);

INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('velcome-voka - Абонентская плата за ТВ', '4404901', 2);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Мегого - Кино и ТВ', '4432421', 2);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Медиатек - TVBox', '424291', 2);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Техноон - Sputniki.by', '4392381', 2);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Эфир - Абонентская плата за ТВ', '381321', 2);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Подключение ТВ', '381341', 2);

INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Afashion.by', '4341161', 3);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Amd.by', '4424021', 3);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Babybike.by', '1519814', 3);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Daflor.by', '4420341', 3);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Hatalik.by', '4398221', 3);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Nalepka.by', '425071', 3);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Udachno.by', '4434511', 3);

INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Штрафы ГАИ', '4325411', 4);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Фотофиксация скорости ГАИ', '381141', 4);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Штраф ГАИ - отсутствие страховки', '4325401', 4);

INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('life :) на № телефона', '4417781', 5);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('velcom - по № телефона', '381861', 5);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('МТС по № телефона', '393931', 5);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('МТС - Домашний интернет', '4270161', 5);

INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Белгазета - подписка', '4393081', 6);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Гойсак - подписка', '399311', 6);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Искра - подписка', '7442346', 6);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Лидская газета - подписка', '232545', 6);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Рыболов - подписка на электронную версию', '4353511', 6);

INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Госпошлина при обращении в суд РБ', '4354401', 8);

INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Таможенная пошлина МПО', '4468941', 7);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Таможенный сбор МПО', '4442131', 7);
INSERT INTO t_payment(F_PAYMENT_NAME, F_RECEIVER_ACCOUNT, F_CATEGORY_ID) VALUES ('Штрафы за АТП', '388301', 7);
